#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]
const id = userInputs[3]
const task = userInputs[4]

switch (cmd) {
  case 'list':
    commands.list()
    break
  case 'delete':
    commands.deleteToDo(id)
    break
  case 'add':
    commands.addTask(id, task)
    break
  default:
    console.log(`I don't understand that command: ${cmd}`)
}
